show:
    path:     /show
    defaults: { _controller: AcmeLearnBundle:Battery:show }

add:
    path:     /add
    defaults: { _controller: AcmeLearnBundle:Battery:add }

del:
    path:     /del
    defaults: { _controller: AcmeLearnBundle:Battery:del }